@startuml
'https://plantuml.com/class-diagram

class Fourmi
{
    + deplacementHasard(g:Grid)
    + deplacerVers(x,y,g:Grid)
    + deplacementValide(newX, newY, g:Grid): Boolean
}

class Soldat extends Fourmi
{
}

class Grid
{
    + getListFourmis()
    - putFourmis(<Occupant> grid, nbFourmis)
    + getGrid()
    + putObstacle(<Occupant> grid, nbObstacles)
    - contientObstacle(x,y): Boolean
    + showGrid()
    - fill()
    + getListObstacles()
    + showListObstacle()
}

class Main
{
    +lancerJeu(g:Grid)
    +avancerTemps(g:Grid)
}

class Occupant
{
    - x
    - y
    + getX(): int
    + getY(): int
    + toString()
    + setX()
    + setY()

}
class Obstacle
{
    + toString()
}
@enduml