@startuml
'https://plantuml.com/sequence-diagram

autonumber

Participant Main
Participant MyOwnTest
Participant Controller
Participant Grid
Participant Queen



Main -> MyOwnTest : run()
MyOwnTest -> Controller : createGrid
MyOwnTest -> Controller : createColony
MyOwnTest -> Controller : putObstacle
MyOwnTest -> Controller : createSoldiers
MyOwnTest -> Controller : play


Controller -> Grid

@enduml